name: arangodart
description: ArangoDB Dart driver
version: 0.0.1
author: Rodrigo <rodamora@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  http: ^0.12.0+2

dev_dependencies:
  pedantic: ^1.0.0
